# Generated by Django 5.2.6 on 2025-10-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clothe_app', '0002_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Razorpay', 'Razorpay'), ('COD', 'Cash on Delivery')], max_length=50),
        ),
    ]
